// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA74fS7cVQXRQm7s4D3tAxtH2zv5grYAW4',
    appId: '1:518459745857:web:6af1e6eb23051c272508c0',
    messagingSenderId: '518459745857',
    projectId: 'sports-injuries-10be1',
    authDomain: 'sports-injuries-10be1.firebaseapp.com',
    storageBucket: 'sports-injuries-10be1.appspot.com',
    measurementId: 'G-E07G14S87Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrT9NXaECGiw6rsPSCrbtA-Lt9NINwKqU',
    appId: '1:518459745857:android:fcdf4ff7b91375b12508c0',
    messagingSenderId: '518459745857',
    projectId: 'sports-injuries-10be1',
    storageBucket: 'sports-injuries-10be1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcavwcUD0OmQ3bm6ff4uGgTserQiuzDDQ',
    appId: '1:518459745857:ios:afa2eb4028d19cd32508c0',
    messagingSenderId: '518459745857',
    projectId: 'sports-injuries-10be1',
    storageBucket: 'sports-injuries-10be1.appspot.com',
    iosBundleId: 'com.example.sportsInjuryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcavwcUD0OmQ3bm6ff4uGgTserQiuzDDQ',
    appId: '1:518459745857:ios:0468fbf748ee71632508c0',
    messagingSenderId: '518459745857',
    projectId: 'sports-injuries-10be1',
    storageBucket: 'sports-injuries-10be1.appspot.com',
    iosBundleId: 'com.example.sportsInjuryApp.RunnerTests',
  );
}
